Python: C:\Python312\python.exe
PYTHONPATH: C:\Users\reube\SmartFarm-API\
DJANGO_SETTINGS_MODULE: smartfarm.settings.local
Traceback (most recent call last):
  File "C:\Users\reube\SmartFarm-API\manage.py", line 11, in main
    from django.core.management import execute_from_command_line
  File "C:\Python312\Lib\site-packages\django\__init__.py", line 1, in <module>
    from django.utils.version import get_version
ModuleNotFoundError: No module named 'django.utils'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\reube\SmartFarm-API\manage.py", line 22, in <module>
    main()
  File "C:\Users\reube\SmartFarm-API\manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
